services:
  docs:
    image: ticketingapi_local_docs
    container_name: ticketingapi_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
#      - ./ticketingapi:/app/ticketingapi:z
    ports:
      - '9000:9000'
    command: /start-docs
